### ISSUE TITLE
AttributeError: 'Strategy' object has no attribute 'set_ft'

### ISSUE THREAD

**Issue by LucianPopaLVP** [TomtomEh/freqtrade-websocket#1]
hello , 
can you please help me implement this into my freqtrade?
i went to the freqtradebot.py and added the line: 

self.strategy.set_ft(self)

around line 66

        # Cache values for 1800 to avoid frequent polling of the exchange for prices
        # Caching only applies to RPC methods, so prices for open trades are still
        # refreshed once every iteration.
        self._sell_rate_cache: TTLCache = TTLCache(maxsize=100, ttl=1800)
        self._buy_rate_cache: TTLCache = TTLCache(maxsize=100, ttl=1800)

        self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
        self.strategy.set_ft(self) 

        # Check config consistency here since strategies can set certain options
        validate_config_consistency(config)

And i get this error :     self.strategy.set_ft(self)
AttributeError: 'Strategy' object has no attribute 'set_ft'

What do i need to add into my startegy to make the bot get infor through this websockets?
Sorry, but i am in process of learning python and don't know all the information yet.
Thank you!

**Comment by AppGonder** [comment]
I have the following error when running

Starting order book for ADA/USDT.
Starting order book for ADA/USDT.
2021-09-06 22:00:22,799 - freqtrade.commands.trade_commands - ERROR - too many values to unpack (expected 2)
2021-09-06 22:00:22,799 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\freqtrade_v1\freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "c:\freqtrade_v1\freqtrade\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "c:\freqtrade_v1\freqtrade\freqtrade\worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "c:\freqtrade_v1\freqtrade\freqtrade\worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "c:\freqtrade_v1\freqtrade\freqtrade\worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "c:\freqtrade_v1\freqtrade\freqtrade\freqtradebot.py", line 193, in process
    self.enter_positions()
  File "c:\freqtrade_v1\freqtrade\freqtrade\freqtradebot.py", line 401, in enter_positions
    trades_created += self.create_trade(pair)
  File "c:\freqtrade_v1\freqtrade\freqtrade\freqtradebot.py", line 443, in create_trade
    (buy, sell) = self.strategy.get_signal(pair, self.strategy.timeframe, analyzed_df)
ValueError: too many values to unpack (expected 2)

**Comment by vishalsawai** [comment]
@LucianPopaLVP do you find any solution yet to implement websocket?

**Comment by LucianPopaLVP** [comment]
> @LucianPopaLVP do you find any solution yet to implement WebSocket?

not in freqreade, but in other scripts outside of the freqtrade. 
https://www.youtube.com/watch?v=d-2GoqQbagI

**Comment by TomtomEh** [comment]
Hi,
it's probably because you are using a standard strategy and not one that inherits from BinanceStream. 
You can implement your own strat based on OBOnlyWSv2bband.py or CombinedBinHAndClucV4WS.py

BinanceStream is used to bypass all freqtrade machinery and provide data directly from websocket
